ARG RUBY_VERSION=3.4.2
FROM ruby:$RUBY_VERSION-slim

WORKDIR /rails

# インストール必要なパッケージ
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    curl \
    postgresql-client \
    git \
    libjemalloc2 \
    libvips \
    libyaml-dev \
    pkg-config \
    libpq-dev && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Bundler のインストール
ENV BUNDLE_PATH=/usr/local/bundle
RUN gem install bundler

# アプリケーション依存のインストール
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリケーションコードのコピー
COPY . .

# ポート公開
EXPOSE 3000

# デフォルトコマンド
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
